[package]
name = "gbench"
description = "GPU benchmark program for Neptune"
version = "0.5.4"
authors = ["porcuquine <porcuquine@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"

byteorder = "1"
lazy_static = "1.4"
generic-array = "0.14"
blake2s_simd = "0.5"

fff = "0.2"
paired = "0.19"
bellperson = "0.6"
triton = { version = "0.2.0", package = "neptune-triton", default-features = false, features = ["opencl"] }
neptune = { path = "../", features=["gpu"] }
